[package]
name = "openinfer-simulator"
version = "0.1.1"
edition = "2021"
description = "Host-side simulator and runtime for OpenInfer graphs."
license = "Apache-2.0"
repository = "https://github.com/arsalan-anwari/openinfer-simulator"
readme = "README.md"

[dependencies]
anyhow = "1"
uuid = { version = "1", features = ["v4", "serde"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
openinfer-dsl = "0.1.3"
rand = "0.8"
memmap2 = "0.9"
rayon = "*"
once_cell = "1"
bytemuck = { version = "1", features = ["derive"] }
ash = "0.38.0"

[build-dependencies]
openinfer-simulator-generator = { version = "0.1.1", path = "generator" }

[dev-dependencies]

[features]
vulkan = []
