// @generated by build.rs. Do not edit.
use anyhow::{anyhow, Result};

use crate::graph::OpAttrs;
use crate::ops::cpu::registry::expect_output;
use crate::tensor::TensorValue;

pub fn popcount_normal_dispatch(_attrs: &OpAttrs, inputs: &[TensorValue], output: Option<&mut TensorValue>) -> Result<()> {
    let out = expect_output(output)?;
    match (&inputs[0], out) {
        (TensorValue::I8(a0), TensorValue::U8(out)) => super::kernels::normal::popcount_i8_normal(a0, out),
        (TensorValue::I16(a0), TensorValue::U8(out)) => super::kernels::normal::popcount_i16_normal(a0, out),
        (TensorValue::I32(a0), TensorValue::U8(out)) => super::kernels::normal::popcount_i32_normal(a0, out),
        (TensorValue::I64(a0), TensorValue::U8(out)) => super::kernels::normal::popcount_i64_normal(a0, out),
        (TensorValue::U8(a0), TensorValue::U8(out)) => super::kernels::normal::popcount_u8_normal(a0, out),
        (TensorValue::U16(a0), TensorValue::U8(out)) => super::kernels::normal::popcount_u16_normal(a0, out),
        (TensorValue::U32(a0), TensorValue::U8(out)) => super::kernels::normal::popcount_u32_normal(a0, out),
        (TensorValue::U64(a0), TensorValue::U8(out)) => super::kernels::normal::popcount_u64_normal(a0, out),
        (TensorValue::I2(a0), TensorValue::U8(out)) => super::kernels::packed::popcount_i2_packed(a0, out),
        (TensorValue::I4(a0), TensorValue::U8(out)) => super::kernels::packed::popcount_i4_packed(a0, out),
        (TensorValue::U2(a0), TensorValue::U8(out)) => super::kernels::packed::popcount_u2_packed(a0, out),
        (TensorValue::U4(a0), TensorValue::U8(out)) => super::kernels::packed::popcount_u4_packed(a0, out),
        _ => Err(anyhow!("dtype mismatch")),
    }
}

