// @generated by build.rs. Do not edit.
use anyhow::{anyhow, Result};

use crate::graph::OpAttrs;
use crate::ops::cpu::registry::expect_output;
use crate::tensor::TensorValue;

pub fn sum_axis_normal_dispatch(_attrs: &OpAttrs, inputs: &[TensorValue], output: Option<&mut TensorValue>) -> Result<()> {
    let out = expect_output(output)?;
    match (&inputs[0], out) {
        (TensorValue::F8(a0), TensorValue::F8(out)) => super::kernels::normal::sum_axis_f8_normal(_attrs, a0, out),
        (TensorValue::F16(a0), TensorValue::F16(out)) => super::kernels::normal::sum_axis_f16_normal(_attrs, a0, out),
        (TensorValue::BF16(a0), TensorValue::BF16(out)) => super::kernels::normal::sum_axis_bf16_normal(_attrs, a0, out),
        (TensorValue::F32(a0), TensorValue::F32(out)) => super::kernels::normal::sum_axis_f32_normal(_attrs, a0, out),
        (TensorValue::F64(a0), TensorValue::F64(out)) => super::kernels::normal::sum_axis_f64_normal(_attrs, a0, out),
        (TensorValue::I8(a0), TensorValue::I8(out)) => super::kernels::normal::sum_axis_i8_normal(_attrs, a0, out),
        (TensorValue::I16(a0), TensorValue::I16(out)) => super::kernels::normal::sum_axis_i16_normal(_attrs, a0, out),
        (TensorValue::I32(a0), TensorValue::I32(out)) => super::kernels::normal::sum_axis_i32_normal(_attrs, a0, out),
        (TensorValue::I64(a0), TensorValue::I64(out)) => super::kernels::normal::sum_axis_i64_normal(_attrs, a0, out),
        (TensorValue::U8(a0), TensorValue::U8(out)) => super::kernels::normal::sum_axis_u8_normal(_attrs, a0, out),
        (TensorValue::U16(a0), TensorValue::U16(out)) => super::kernels::normal::sum_axis_u16_normal(_attrs, a0, out),
        (TensorValue::U32(a0), TensorValue::U32(out)) => super::kernels::normal::sum_axis_u32_normal(_attrs, a0, out),
        (TensorValue::U64(a0), TensorValue::U64(out)) => super::kernels::normal::sum_axis_u64_normal(_attrs, a0, out),
        (TensorValue::I1(a0), TensorValue::I1(out)) => super::kernels::packed::sum_axis_i1_packed(_attrs, a0, out),
        (TensorValue::I2(a0), TensorValue::I2(out)) => super::kernels::packed::sum_axis_i2_packed(_attrs, a0, out),
        (TensorValue::I4(a0), TensorValue::I4(out)) => super::kernels::packed::sum_axis_i4_packed(_attrs, a0, out),
        (TensorValue::U1(a0), TensorValue::U1(out)) => super::kernels::packed::sum_axis_u1_packed(_attrs, a0, out),
        (TensorValue::U2(a0), TensorValue::U2(out)) => super::kernels::packed::sum_axis_u2_packed(_attrs, a0, out),
        (TensorValue::U4(a0), TensorValue::U4(out)) => super::kernels::packed::sum_axis_u4_packed(_attrs, a0, out),
        _ => Err(anyhow!("dtype mismatch")),
    }
}

pub fn sum_axis_accumulate_dispatch(_attrs: &OpAttrs, inputs: &[TensorValue], output: Option<&mut TensorValue>) -> Result<()> {
    let out = expect_output(output)?;
    match (&inputs[0], out) {
        (TensorValue::I1(a0), TensorValue::I8(out)) => super::kernels::accumulate::sum_axis_i1_accumulate_i8(_attrs, a0, out),
        (TensorValue::I1(a0), TensorValue::I16(out)) => super::kernels::accumulate::sum_axis_i1_accumulate_i16(_attrs, a0, out),
        (TensorValue::I1(a0), TensorValue::I32(out)) => super::kernels::accumulate::sum_axis_i1_accumulate_i32(_attrs, a0, out),
        (TensorValue::I1(a0), TensorValue::I64(out)) => super::kernels::accumulate::sum_axis_i1_accumulate_i64(_attrs, a0, out),
        (TensorValue::I2(a0), TensorValue::I8(out)) => super::kernels::accumulate::sum_axis_i2_accumulate_i8(_attrs, a0, out),
        (TensorValue::I2(a0), TensorValue::I16(out)) => super::kernels::accumulate::sum_axis_i2_accumulate_i16(_attrs, a0, out),
        (TensorValue::I2(a0), TensorValue::I32(out)) => super::kernels::accumulate::sum_axis_i2_accumulate_i32(_attrs, a0, out),
        (TensorValue::I2(a0), TensorValue::I64(out)) => super::kernels::accumulate::sum_axis_i2_accumulate_i64(_attrs, a0, out),
        (TensorValue::I4(a0), TensorValue::I8(out)) => super::kernels::accumulate::sum_axis_i4_accumulate_i8(_attrs, a0, out),
        (TensorValue::I4(a0), TensorValue::I16(out)) => super::kernels::accumulate::sum_axis_i4_accumulate_i16(_attrs, a0, out),
        (TensorValue::I4(a0), TensorValue::I32(out)) => super::kernels::accumulate::sum_axis_i4_accumulate_i32(_attrs, a0, out),
        (TensorValue::I4(a0), TensorValue::I64(out)) => super::kernels::accumulate::sum_axis_i4_accumulate_i64(_attrs, a0, out),
        (TensorValue::I8(a0), TensorValue::I16(out)) => super::kernels::accumulate::sum_axis_i8_accumulate_i16(_attrs, a0, out),
        (TensorValue::I8(a0), TensorValue::I32(out)) => super::kernels::accumulate::sum_axis_i8_accumulate_i32(_attrs, a0, out),
        (TensorValue::I8(a0), TensorValue::I64(out)) => super::kernels::accumulate::sum_axis_i8_accumulate_i64(_attrs, a0, out),
        (TensorValue::I16(a0), TensorValue::I32(out)) => super::kernels::accumulate::sum_axis_i16_accumulate_i32(_attrs, a0, out),
        (TensorValue::I16(a0), TensorValue::I64(out)) => super::kernels::accumulate::sum_axis_i16_accumulate_i64(_attrs, a0, out),
        (TensorValue::I32(a0), TensorValue::I64(out)) => super::kernels::accumulate::sum_axis_i32_accumulate_i64(_attrs, a0, out),
        (TensorValue::U1(a0), TensorValue::U8(out)) => super::kernels::accumulate::sum_axis_u1_accumulate_u8(_attrs, a0, out),
        (TensorValue::U1(a0), TensorValue::U16(out)) => super::kernels::accumulate::sum_axis_u1_accumulate_u16(_attrs, a0, out),
        (TensorValue::U1(a0), TensorValue::U32(out)) => super::kernels::accumulate::sum_axis_u1_accumulate_u32(_attrs, a0, out),
        (TensorValue::U1(a0), TensorValue::U64(out)) => super::kernels::accumulate::sum_axis_u1_accumulate_u64(_attrs, a0, out),
        (TensorValue::U2(a0), TensorValue::U8(out)) => super::kernels::accumulate::sum_axis_u2_accumulate_u8(_attrs, a0, out),
        (TensorValue::U2(a0), TensorValue::U16(out)) => super::kernels::accumulate::sum_axis_u2_accumulate_u16(_attrs, a0, out),
        (TensorValue::U2(a0), TensorValue::U32(out)) => super::kernels::accumulate::sum_axis_u2_accumulate_u32(_attrs, a0, out),
        (TensorValue::U2(a0), TensorValue::U64(out)) => super::kernels::accumulate::sum_axis_u2_accumulate_u64(_attrs, a0, out),
        (TensorValue::U4(a0), TensorValue::U8(out)) => super::kernels::accumulate::sum_axis_u4_accumulate_u8(_attrs, a0, out),
        (TensorValue::U4(a0), TensorValue::U16(out)) => super::kernels::accumulate::sum_axis_u4_accumulate_u16(_attrs, a0, out),
        (TensorValue::U4(a0), TensorValue::U32(out)) => super::kernels::accumulate::sum_axis_u4_accumulate_u32(_attrs, a0, out),
        (TensorValue::U4(a0), TensorValue::U64(out)) => super::kernels::accumulate::sum_axis_u4_accumulate_u64(_attrs, a0, out),
        (TensorValue::U8(a0), TensorValue::U16(out)) => super::kernels::accumulate::sum_axis_u8_accumulate_u16(_attrs, a0, out),
        (TensorValue::U8(a0), TensorValue::U32(out)) => super::kernels::accumulate::sum_axis_u8_accumulate_u32(_attrs, a0, out),
        (TensorValue::U8(a0), TensorValue::U64(out)) => super::kernels::accumulate::sum_axis_u8_accumulate_u64(_attrs, a0, out),
        (TensorValue::U16(a0), TensorValue::U32(out)) => super::kernels::accumulate::sum_axis_u16_accumulate_u32(_attrs, a0, out),
        (TensorValue::U16(a0), TensorValue::U64(out)) => super::kernels::accumulate::sum_axis_u16_accumulate_u64(_attrs, a0, out),
        (TensorValue::U32(a0), TensorValue::U64(out)) => super::kernels::accumulate::sum_axis_u32_accumulate_u64(_attrs, a0, out),
        _ => Err(anyhow!("dtype mismatch")),
    }
}
