// @generated by build.rs. Do not edit.
use anyhow::{anyhow, Result};

use crate::graph::OpAttrs;
use crate::ops::cpu::registry::expect_output;
use crate::tensor::TensorValue;

pub fn xor_normal_dispatch(_attrs: &OpAttrs, inputs: &[TensorValue], output: Option<&mut TensorValue>) -> Result<()> {
    let out = expect_output(output)?;
    match (&inputs[0], &inputs[1], out) {
        (TensorValue::I8(a0), TensorValue::I8(a1), TensorValue::I8(out)) => super::kernels::normal::xor_i8_normal(a0, a1, out),
        (TensorValue::I16(a0), TensorValue::I16(a1), TensorValue::I16(out)) => super::kernels::normal::xor_i16_normal(a0, a1, out),
        (TensorValue::I32(a0), TensorValue::I32(a1), TensorValue::I32(out)) => super::kernels::normal::xor_i32_normal(a0, a1, out),
        (TensorValue::I64(a0), TensorValue::I64(a1), TensorValue::I64(out)) => super::kernels::normal::xor_i64_normal(a0, a1, out),
        (TensorValue::U8(a0), TensorValue::U8(a1), TensorValue::U8(out)) => super::kernels::normal::xor_u8_normal(a0, a1, out),
        (TensorValue::U16(a0), TensorValue::U16(a1), TensorValue::U16(out)) => super::kernels::normal::xor_u16_normal(a0, a1, out),
        (TensorValue::U32(a0), TensorValue::U32(a1), TensorValue::U32(out)) => super::kernels::normal::xor_u32_normal(a0, a1, out),
        (TensorValue::U64(a0), TensorValue::U64(a1), TensorValue::U64(out)) => super::kernels::normal::xor_u64_normal(a0, a1, out),
        (TensorValue::I1(a0), TensorValue::I1(a1), TensorValue::I1(out)) => super::kernels::packed::xor_i1_packed(a0, a1, out),
        (TensorValue::I2(a0), TensorValue::I2(a1), TensorValue::I2(out)) => super::kernels::packed::xor_i2_packed(a0, a1, out),
        (TensorValue::I4(a0), TensorValue::I4(a1), TensorValue::I4(out)) => super::kernels::packed::xor_i4_packed(a0, a1, out),
        (TensorValue::U1(a0), TensorValue::U1(a1), TensorValue::U1(out)) => super::kernels::packed::xor_u1_packed(a0, a1, out),
        (TensorValue::U2(a0), TensorValue::U2(a1), TensorValue::U2(out)) => super::kernels::packed::xor_u2_packed(a0, a1, out),
        (TensorValue::U4(a0), TensorValue::U4(a1), TensorValue::U4(out)) => super::kernels::packed::xor_u4_packed(a0, a1, out),
        (TensorValue::Bool(a0), TensorValue::Bool(a1), TensorValue::Bool(out)) => super::kernels::normal::xor_bool_normal(a0, a1, out),
        _ => Err(anyhow!("dtype mismatch")),
    }
}

pub fn xor_inplace_dispatch(_attrs: &OpAttrs, inputs: &[TensorValue], output: Option<&mut TensorValue>) -> Result<()> {
    let out = expect_output(output)?;
    match (out, &inputs[1]) {
        (TensorValue::I8(a0), TensorValue::I8(a1)) => super::kernels::normal::xor_i8_inplace(a0, a1),
        (TensorValue::I16(a0), TensorValue::I16(a1)) => super::kernels::normal::xor_i16_inplace(a0, a1),
        (TensorValue::I32(a0), TensorValue::I32(a1)) => super::kernels::normal::xor_i32_inplace(a0, a1),
        (TensorValue::I64(a0), TensorValue::I64(a1)) => super::kernels::normal::xor_i64_inplace(a0, a1),
        (TensorValue::U8(a0), TensorValue::U8(a1)) => super::kernels::normal::xor_u8_inplace(a0, a1),
        (TensorValue::U16(a0), TensorValue::U16(a1)) => super::kernels::normal::xor_u16_inplace(a0, a1),
        (TensorValue::U32(a0), TensorValue::U32(a1)) => super::kernels::normal::xor_u32_inplace(a0, a1),
        (TensorValue::U64(a0), TensorValue::U64(a1)) => super::kernels::normal::xor_u64_inplace(a0, a1),
        (TensorValue::I1(a0), TensorValue::I1(a1)) => super::kernels::packed::xor_i1_packed_inplace(a0, a1),
        (TensorValue::I2(a0), TensorValue::I2(a1)) => super::kernels::packed::xor_i2_packed_inplace(a0, a1),
        (TensorValue::I4(a0), TensorValue::I4(a1)) => super::kernels::packed::xor_i4_packed_inplace(a0, a1),
        (TensorValue::U1(a0), TensorValue::U1(a1)) => super::kernels::packed::xor_u1_packed_inplace(a0, a1),
        (TensorValue::U2(a0), TensorValue::U2(a1)) => super::kernels::packed::xor_u2_packed_inplace(a0, a1),
        (TensorValue::U4(a0), TensorValue::U4(a1)) => super::kernels::packed::xor_u4_packed_inplace(a0, a1),
        (TensorValue::Bool(a0), TensorValue::Bool(a1)) => super::kernels::normal::xor_bool_inplace(a0, a1),
        _ => Err(anyhow!("dtype mismatch")),
    }
}

