// @generated by build.rs. Do not edit.
use anyhow::{anyhow, Result};

use crate::graph::OpAttrs;
use crate::ops::cpu::registry::expect_output;
use crate::tensor::TensorValue;

pub fn is_nan_normal_dispatch(_attrs: &OpAttrs, inputs: &[TensorValue], output: Option<&mut TensorValue>) -> Result<()> {
    let out = expect_output(output)?;
    match (&inputs[0], out) {
        (TensorValue::F8(a0), TensorValue::Bool(out)) => super::kernels::normal::is_nan_f8_normal(a0, out),
        (TensorValue::F16(a0), TensorValue::Bool(out)) => super::kernels::normal::is_nan_f16_normal(a0, out),
        (TensorValue::BF16(a0), TensorValue::Bool(out)) => super::kernels::normal::is_nan_bf16_normal(a0, out),
        (TensorValue::F32(a0), TensorValue::Bool(out)) => super::kernels::normal::is_nan_f32_normal(a0, out),
        (TensorValue::F64(a0), TensorValue::Bool(out)) => super::kernels::normal::is_nan_f64_normal(a0, out),
        _ => Err(anyhow!("dtype mismatch")),
    }
}

