// @generated by build.rs. Do not edit.
use anyhow::{anyhow, Result};

use crate::graph::OpAttrs;
use crate::ops::cpu::registry::expect_output;
use crate::tensor::TensorValue;

pub fn gt_normal_dispatch(_attrs: &OpAttrs, inputs: &[TensorValue], output: Option<&mut TensorValue>) -> Result<()> {
    let out = expect_output(output)?;
    match (&inputs[0], &inputs[1], out) {
        (TensorValue::F8(a0), TensorValue::F8(a1), TensorValue::Bool(out)) => super::kernels::normal::gt_f8_normal(a0, a1, out),
        (TensorValue::F16(a0), TensorValue::F16(a1), TensorValue::Bool(out)) => super::kernels::normal::gt_f16_normal(a0, a1, out),
        (TensorValue::BF16(a0), TensorValue::BF16(a1), TensorValue::Bool(out)) => super::kernels::normal::gt_bf16_normal(a0, a1, out),
        (TensorValue::F32(a0), TensorValue::F32(a1), TensorValue::Bool(out)) => super::kernels::normal::gt_f32_normal(a0, a1, out),
        (TensorValue::F64(a0), TensorValue::F64(a1), TensorValue::Bool(out)) => super::kernels::normal::gt_f64_normal(a0, a1, out),
        (TensorValue::I8(a0), TensorValue::I8(a1), TensorValue::Bool(out)) => super::kernels::normal::gt_i8_normal(a0, a1, out),
        (TensorValue::I16(a0), TensorValue::I16(a1), TensorValue::Bool(out)) => super::kernels::normal::gt_i16_normal(a0, a1, out),
        (TensorValue::I32(a0), TensorValue::I32(a1), TensorValue::Bool(out)) => super::kernels::normal::gt_i32_normal(a0, a1, out),
        (TensorValue::I64(a0), TensorValue::I64(a1), TensorValue::Bool(out)) => super::kernels::normal::gt_i64_normal(a0, a1, out),
        (TensorValue::U8(a0), TensorValue::U8(a1), TensorValue::Bool(out)) => super::kernels::normal::gt_u8_normal(a0, a1, out),
        (TensorValue::U16(a0), TensorValue::U16(a1), TensorValue::Bool(out)) => super::kernels::normal::gt_u16_normal(a0, a1, out),
        (TensorValue::U32(a0), TensorValue::U32(a1), TensorValue::Bool(out)) => super::kernels::normal::gt_u32_normal(a0, a1, out),
        (TensorValue::U64(a0), TensorValue::U64(a1), TensorValue::Bool(out)) => super::kernels::normal::gt_u64_normal(a0, a1, out),
        (TensorValue::I1(a0), TensorValue::I1(a1), TensorValue::Bool(out)) => super::kernels::packed::gt_i1_packed(a0, a1, out),
        (TensorValue::I2(a0), TensorValue::I2(a1), TensorValue::Bool(out)) => super::kernels::packed::gt_i2_packed(a0, a1, out),
        (TensorValue::I4(a0), TensorValue::I4(a1), TensorValue::Bool(out)) => super::kernels::packed::gt_i4_packed(a0, a1, out),
        (TensorValue::U1(a0), TensorValue::U1(a1), TensorValue::Bool(out)) => super::kernels::packed::gt_u1_packed(a0, a1, out),
        (TensorValue::U2(a0), TensorValue::U2(a1), TensorValue::Bool(out)) => super::kernels::packed::gt_u2_packed(a0, a1, out),
        (TensorValue::U4(a0), TensorValue::U4(a1), TensorValue::Bool(out)) => super::kernels::packed::gt_u4_packed(a0, a1, out),
        _ => Err(anyhow!("dtype mismatch")),
    }
}

