// @generated by build.rs. Do not edit.
use anyhow::{anyhow, Result};

use crate::graph::OpAttrs;
use crate::ops::cpu::registry::expect_output;
use crate::tensor::TensorValue;

pub fn rem_normal_dispatch(_attrs: &OpAttrs, inputs: &[TensorValue], output: Option<&mut TensorValue>) -> Result<()> {
    let out = expect_output(output)?;
    match (&inputs[0], &inputs[1], out) {
        (TensorValue::I8(a0), TensorValue::I8(a1), TensorValue::I8(out)) => super::kernels::normal::rem_i8_normal(a0, a1, out),
        (TensorValue::I16(a0), TensorValue::I16(a1), TensorValue::I16(out)) => super::kernels::normal::rem_i16_normal(a0, a1, out),
        (TensorValue::I32(a0), TensorValue::I32(a1), TensorValue::I32(out)) => super::kernels::normal::rem_i32_normal(a0, a1, out),
        (TensorValue::I64(a0), TensorValue::I64(a1), TensorValue::I64(out)) => super::kernels::normal::rem_i64_normal(a0, a1, out),
        (TensorValue::U8(a0), TensorValue::U8(a1), TensorValue::U8(out)) => super::kernels::normal::rem_u8_normal(a0, a1, out),
        (TensorValue::U16(a0), TensorValue::U16(a1), TensorValue::U16(out)) => super::kernels::normal::rem_u16_normal(a0, a1, out),
        (TensorValue::U32(a0), TensorValue::U32(a1), TensorValue::U32(out)) => super::kernels::normal::rem_u32_normal(a0, a1, out),
        (TensorValue::U64(a0), TensorValue::U64(a1), TensorValue::U64(out)) => super::kernels::normal::rem_u64_normal(a0, a1, out),
        (TensorValue::I4(a0), TensorValue::I4(a1), TensorValue::I4(out)) => super::kernels::packed::rem_i4_packed(a0, a1, out),
        (TensorValue::U4(a0), TensorValue::U4(a1), TensorValue::U4(out)) => super::kernels::packed::rem_u4_packed(a0, a1, out),
        _ => Err(anyhow!("dtype mismatch")),
    }
}

pub fn rem_inplace_dispatch(_attrs: &OpAttrs, inputs: &[TensorValue], output: Option<&mut TensorValue>) -> Result<()> {
    let out = expect_output(output)?;
    match (out, &inputs[1]) {
        (TensorValue::I8(a0), TensorValue::I8(a1)) => super::kernels::normal::rem_i8_inplace(a0, a1),
        (TensorValue::I16(a0), TensorValue::I16(a1)) => super::kernels::normal::rem_i16_inplace(a0, a1),
        (TensorValue::I32(a0), TensorValue::I32(a1)) => super::kernels::normal::rem_i32_inplace(a0, a1),
        (TensorValue::I64(a0), TensorValue::I64(a1)) => super::kernels::normal::rem_i64_inplace(a0, a1),
        (TensorValue::U8(a0), TensorValue::U8(a1)) => super::kernels::normal::rem_u8_inplace(a0, a1),
        (TensorValue::U16(a0), TensorValue::U16(a1)) => super::kernels::normal::rem_u16_inplace(a0, a1),
        (TensorValue::U32(a0), TensorValue::U32(a1)) => super::kernels::normal::rem_u32_inplace(a0, a1),
        (TensorValue::U64(a0), TensorValue::U64(a1)) => super::kernels::normal::rem_u64_inplace(a0, a1),
        (TensorValue::I4(a0), TensorValue::I4(a1)) => super::kernels::packed::rem_i4_packed_inplace(a0, a1),
        (TensorValue::U4(a0), TensorValue::U4(a1)) => super::kernels::packed::rem_u4_packed_inplace(a0, a1),
        _ => Err(anyhow!("dtype mismatch")),
    }
}

