// @generated by build.rs. Do not edit.
use anyhow::{anyhow, Result};

use crate::graph::OpAttrs;
use crate::ops::cpu::registry::expect_output;
use crate::tensor::TensorValue;

pub fn not_normal_dispatch(_attrs: &OpAttrs, inputs: &[TensorValue], output: Option<&mut TensorValue>) -> Result<()> {
    let out = expect_output(output)?;
    match (&inputs[0], out) {
        (TensorValue::I8(a0), TensorValue::I8(out)) => super::kernels::normal::not_i8_normal(a0, out),
        (TensorValue::I16(a0), TensorValue::I16(out)) => super::kernels::normal::not_i16_normal(a0, out),
        (TensorValue::I32(a0), TensorValue::I32(out)) => super::kernels::normal::not_i32_normal(a0, out),
        (TensorValue::I64(a0), TensorValue::I64(out)) => super::kernels::normal::not_i64_normal(a0, out),
        (TensorValue::U8(a0), TensorValue::U8(out)) => super::kernels::normal::not_u8_normal(a0, out),
        (TensorValue::U16(a0), TensorValue::U16(out)) => super::kernels::normal::not_u16_normal(a0, out),
        (TensorValue::U32(a0), TensorValue::U32(out)) => super::kernels::normal::not_u32_normal(a0, out),
        (TensorValue::U64(a0), TensorValue::U64(out)) => super::kernels::normal::not_u64_normal(a0, out),
        (TensorValue::I1(a0), TensorValue::I1(out)) => super::kernels::packed::not_i1_packed(a0, out),
        (TensorValue::I2(a0), TensorValue::I2(out)) => super::kernels::packed::not_i2_packed(a0, out),
        (TensorValue::I4(a0), TensorValue::I4(out)) => super::kernels::packed::not_i4_packed(a0, out),
        (TensorValue::U1(a0), TensorValue::U1(out)) => super::kernels::packed::not_u1_packed(a0, out),
        (TensorValue::U2(a0), TensorValue::U2(out)) => super::kernels::packed::not_u2_packed(a0, out),
        (TensorValue::U4(a0), TensorValue::U4(out)) => super::kernels::packed::not_u4_packed(a0, out),
        (TensorValue::Bool(a0), TensorValue::Bool(out)) => super::kernels::normal::not_bool_normal(a0, out),
        _ => Err(anyhow!("dtype mismatch")),
    }
}

pub fn not_inplace_dispatch(_attrs: &OpAttrs, _inputs: &[TensorValue], output: Option<&mut TensorValue>) -> Result<()> {
    let out = expect_output(output)?;
    match out {
        TensorValue::I8(a) => super::kernels::normal::not_i8_inplace(a),
        TensorValue::I16(a) => super::kernels::normal::not_i16_inplace(a),
        TensorValue::I32(a) => super::kernels::normal::not_i32_inplace(a),
        TensorValue::I64(a) => super::kernels::normal::not_i64_inplace(a),
        TensorValue::U8(a) => super::kernels::normal::not_u8_inplace(a),
        TensorValue::U16(a) => super::kernels::normal::not_u16_inplace(a),
        TensorValue::U32(a) => super::kernels::normal::not_u32_inplace(a),
        TensorValue::U64(a) => super::kernels::normal::not_u64_inplace(a),
        TensorValue::I1(a) => super::kernels::packed::not_i1_packed_inplace(a),
        TensorValue::I2(a) => super::kernels::packed::not_i2_packed_inplace(a),
        TensorValue::I4(a) => super::kernels::packed::not_i4_packed_inplace(a),
        TensorValue::U1(a) => super::kernels::packed::not_u1_packed_inplace(a),
        TensorValue::U2(a) => super::kernels::packed::not_u2_packed_inplace(a),
        TensorValue::U4(a) => super::kernels::packed::not_u4_packed_inplace(a),
        TensorValue::Bool(a) => super::kernels::normal::not_bool_inplace(a),
        _ => Err(anyhow!("dtype mismatch")),
    }
}

