// @generated by build.rs. Do not edit.
use anyhow::{anyhow, Result};

use crate::graph::OpAttrs;
use crate::ops::cpu::registry::expect_output;
use crate::tensor::TensorValue;

pub fn recip_normal_dispatch(_attrs: &OpAttrs, inputs: &[TensorValue], output: Option<&mut TensorValue>) -> Result<()> {
    let out = expect_output(output)?;
    match (&inputs[0], out) {
        (TensorValue::F8(a0), TensorValue::F8(out)) => super::kernels::normal::recip_f8_normal(_attrs, a0, out),
        (TensorValue::F16(a0), TensorValue::F16(out)) => super::kernels::normal::recip_f16_normal(_attrs, a0, out),
        (TensorValue::BF16(a0), TensorValue::BF16(out)) => super::kernels::normal::recip_bf16_normal(_attrs, a0, out),
        (TensorValue::F32(a0), TensorValue::F32(out)) => super::kernels::normal::recip_f32_normal(_attrs, a0, out),
        (TensorValue::F64(a0), TensorValue::F64(out)) => super::kernels::normal::recip_f64_normal(_attrs, a0, out),
        _ => Err(anyhow!("dtype mismatch")),
    }
}

pub fn recip_inplace_dispatch(_attrs: &OpAttrs, _inputs: &[TensorValue], output: Option<&mut TensorValue>) -> Result<()> {
    let out = expect_output(output)?;
    match out {
        TensorValue::F8(a) => super::kernels::normal::recip_f8_inplace(_attrs, a),
        TensorValue::F16(a) => super::kernels::normal::recip_f16_inplace(_attrs, a),
        TensorValue::BF16(a) => super::kernels::normal::recip_bf16_inplace(_attrs, a),
        TensorValue::F32(a) => super::kernels::normal::recip_f32_inplace(_attrs, a),
        TensorValue::F64(a) => super::kernels::normal::recip_f64_inplace(_attrs, a),
        _ => Err(anyhow!("dtype mismatch")),
    }
}

