// @generated by build.rs. Do not edit.
use anyhow::{anyhow, Result};

use crate::graph::OpAttrs;
use crate::ops::cpu::registry::expect_output;
use crate::tensor::TensorValue;

pub fn fma_normal_dispatch(_attrs: &OpAttrs, inputs: &[TensorValue], output: Option<&mut TensorValue>) -> Result<()> {
    let out = expect_output(output)?;
    match (&inputs[0], &inputs[1], &inputs[2], out) {
        (TensorValue::F8(a0), TensorValue::F8(a1), TensorValue::F8(a2), TensorValue::F8(out)) => super::kernels::normal::fma_f8_normal(a0, a1, a2, out),
        (TensorValue::F16(a0), TensorValue::F16(a1), TensorValue::F16(a2), TensorValue::F16(out)) => super::kernels::normal::fma_f16_normal(a0, a1, a2, out),
        (TensorValue::BF16(a0), TensorValue::BF16(a1), TensorValue::BF16(a2), TensorValue::BF16(out)) => super::kernels::normal::fma_bf16_normal(a0, a1, a2, out),
        (TensorValue::F32(a0), TensorValue::F32(a1), TensorValue::F32(a2), TensorValue::F32(out)) => super::kernels::normal::fma_f32_normal(a0, a1, a2, out),
        (TensorValue::F64(a0), TensorValue::F64(a1), TensorValue::F64(a2), TensorValue::F64(out)) => super::kernels::normal::fma_f64_normal(a0, a1, a2, out),
        _ => Err(anyhow!("dtype mismatch")),
    }
}

pub fn fma_inplace_dispatch(_attrs: &OpAttrs, inputs: &[TensorValue], output: Option<&mut TensorValue>) -> Result<()> {
    let out = expect_output(output)?;
    match (out, &inputs[1], &inputs[2]) {
        (TensorValue::F8(a0), TensorValue::F8(a1), TensorValue::F8(a2)) => super::kernels::normal::fma_f8_inplace(a0, a1, a2),
        (TensorValue::F16(a0), TensorValue::F16(a1), TensorValue::F16(a2)) => super::kernels::normal::fma_f16_inplace(a0, a1, a2),
        (TensorValue::BF16(a0), TensorValue::BF16(a1), TensorValue::BF16(a2)) => super::kernels::normal::fma_bf16_inplace(a0, a1, a2),
        (TensorValue::F32(a0), TensorValue::F32(a1), TensorValue::F32(a2)) => super::kernels::normal::fma_f32_inplace(a0, a1, a2),
        (TensorValue::F64(a0), TensorValue::F64(a1), TensorValue::F64(a2)) => super::kernels::normal::fma_f64_inplace(a0, a1, a2),
        _ => Err(anyhow!("dtype mismatch")),
    }
}

