// @generated by build.rs. Do not edit.
use anyhow::{anyhow, Result};

use crate::graph::OpAttrs;
use crate::ops::cpu::registry::expect_output;
use crate::tensor::TensorValue;

pub fn abs_normal_dispatch(_attrs: &OpAttrs, inputs: &[TensorValue], output: Option<&mut TensorValue>) -> Result<()> {
    let out = expect_output(output)?;
    match (&inputs[0], out) {
        (TensorValue::F8(a0), TensorValue::F8(out)) => super::kernels::normal::abs_f8_normal(a0, out),
        (TensorValue::BF16(a0), TensorValue::BF16(out)) => super::kernels::normal::abs_bf16_normal(a0, out),
        (TensorValue::F16(a0), TensorValue::F16(out)) => super::kernels::normal::abs_f16_normal(a0, out),
        (TensorValue::F32(a0), TensorValue::F32(out)) => super::kernels::normal::abs_f32_normal(a0, out),
        (TensorValue::F64(a0), TensorValue::F64(out)) => super::kernels::normal::abs_f64_normal(a0, out),
        (TensorValue::I1(a0), TensorValue::I1(out)) => super::kernels::packed::abs_i1_packed(a0, out),
        (TensorValue::I2(a0), TensorValue::I2(out)) => super::kernels::packed::abs_i2_packed(a0, out),
        (TensorValue::I4(a0), TensorValue::I4(out)) => super::kernels::packed::abs_i4_packed(a0, out),
        (TensorValue::I8(a0), TensorValue::I8(out)) => super::kernels::normal::abs_i8_normal(a0, out),
        (TensorValue::I16(a0), TensorValue::I16(out)) => super::kernels::normal::abs_i16_normal(a0, out),
        (TensorValue::I32(a0), TensorValue::I32(out)) => super::kernels::normal::abs_i32_normal(a0, out),
        (TensorValue::I64(a0), TensorValue::I64(out)) => super::kernels::normal::abs_i64_normal(a0, out),
        _ => Err(anyhow!("dtype mismatch")),
    }
}

pub fn abs_inplace_dispatch(_attrs: &OpAttrs, _inputs: &[TensorValue], output: Option<&mut TensorValue>) -> Result<()> {
    let out = expect_output(output)?;
    match out {
        TensorValue::F8(a) => super::kernels::normal::abs_f8_inplace(a),
        TensorValue::BF16(a) => super::kernels::normal::abs_bf16_inplace(a),
        TensorValue::F16(a) => super::kernels::normal::abs_f16_inplace(a),
        TensorValue::F32(a) => super::kernels::normal::abs_f32_inplace(a),
        TensorValue::F64(a) => super::kernels::normal::abs_f64_inplace(a),
        TensorValue::I1(a) => super::kernels::packed::abs_i1_packed_inplace(a),
        TensorValue::I2(a) => super::kernels::packed::abs_i2_packed_inplace(a),
        TensorValue::I4(a) => super::kernels::packed::abs_i4_packed_inplace(a),
        TensorValue::I8(a) => super::kernels::normal::abs_i8_inplace(a),
        TensorValue::I16(a) => super::kernels::normal::abs_i16_inplace(a),
        TensorValue::I32(a) => super::kernels::normal::abs_i32_inplace(a),
        TensorValue::I64(a) => super::kernels::normal::abs_i64_inplace(a),
        _ => Err(anyhow!("dtype mismatch")),
    }
}

pub fn abs_accumulate_dispatch(_attrs: &OpAttrs, inputs: &[TensorValue], output: Option<&mut TensorValue>) -> Result<()> {
    let out = expect_output(output)?;
    match (&inputs[0], out) {
        (TensorValue::I1(a0), TensorValue::I8(out)) => super::kernels::accumulate::abs_i1_accumulate_i8(a0, out),
        (TensorValue::I1(a0), TensorValue::I16(out)) => super::kernels::accumulate::abs_i1_accumulate_i16(a0, out),
        (TensorValue::I1(a0), TensorValue::I32(out)) => super::kernels::accumulate::abs_i1_accumulate_i32(a0, out),
        (TensorValue::I1(a0), TensorValue::I64(out)) => super::kernels::accumulate::abs_i1_accumulate_i64(a0, out),
        (TensorValue::I2(a0), TensorValue::I8(out)) => super::kernels::accumulate::abs_i2_accumulate_i8(a0, out),
        (TensorValue::I2(a0), TensorValue::I16(out)) => super::kernels::accumulate::abs_i2_accumulate_i16(a0, out),
        (TensorValue::I2(a0), TensorValue::I32(out)) => super::kernels::accumulate::abs_i2_accumulate_i32(a0, out),
        (TensorValue::I2(a0), TensorValue::I64(out)) => super::kernels::accumulate::abs_i2_accumulate_i64(a0, out),
        (TensorValue::I4(a0), TensorValue::I8(out)) => super::kernels::accumulate::abs_i4_accumulate_i8(a0, out),
        (TensorValue::I4(a0), TensorValue::I16(out)) => super::kernels::accumulate::abs_i4_accumulate_i16(a0, out),
        (TensorValue::I4(a0), TensorValue::I32(out)) => super::kernels::accumulate::abs_i4_accumulate_i32(a0, out),
        (TensorValue::I4(a0), TensorValue::I64(out)) => super::kernels::accumulate::abs_i4_accumulate_i64(a0, out),
        (TensorValue::I8(a0), TensorValue::I16(out)) => super::kernels::accumulate::abs_i8_accumulate_i16(a0, out),
        (TensorValue::I8(a0), TensorValue::I32(out)) => super::kernels::accumulate::abs_i8_accumulate_i32(a0, out),
        (TensorValue::I8(a0), TensorValue::I64(out)) => super::kernels::accumulate::abs_i8_accumulate_i64(a0, out),
        (TensorValue::I16(a0), TensorValue::I32(out)) => super::kernels::accumulate::abs_i16_accumulate_i32(a0, out),
        (TensorValue::I16(a0), TensorValue::I64(out)) => super::kernels::accumulate::abs_i16_accumulate_i64(a0, out),
        (TensorValue::I32(a0), TensorValue::I64(out)) => super::kernels::accumulate::abs_i32_accumulate_i64(a0, out),
        _ => Err(anyhow!("dtype mismatch")),
    }
}
