// @generated by build.rs. Do not edit.
use anyhow::{anyhow, Result};

use crate::graph::OpAttrs;
use crate::ops::cpu::registry::expect_output;
use crate::tensor::TensorValue;

pub fn is_neg_normal_dispatch(_attrs: &OpAttrs, inputs: &[TensorValue], output: Option<&mut TensorValue>) -> Result<()> {
    let out = expect_output(output)?;
    match (&inputs[0], out) {
        (TensorValue::F8(a0), TensorValue::Bool(out)) => super::kernels::normal::is_neg_f8_normal(a0, out),
        (TensorValue::F16(a0), TensorValue::Bool(out)) => super::kernels::normal::is_neg_f16_normal(a0, out),
        (TensorValue::BF16(a0), TensorValue::Bool(out)) => super::kernels::normal::is_neg_bf16_normal(a0, out),
        (TensorValue::F32(a0), TensorValue::Bool(out)) => super::kernels::normal::is_neg_f32_normal(a0, out),
        (TensorValue::F64(a0), TensorValue::Bool(out)) => super::kernels::normal::is_neg_f64_normal(a0, out),
        (TensorValue::I8(a0), TensorValue::Bool(out)) => super::kernels::normal::is_neg_i8_normal(a0, out),
        (TensorValue::I16(a0), TensorValue::Bool(out)) => super::kernels::normal::is_neg_i16_normal(a0, out),
        (TensorValue::I32(a0), TensorValue::Bool(out)) => super::kernels::normal::is_neg_i32_normal(a0, out),
        (TensorValue::I64(a0), TensorValue::Bool(out)) => super::kernels::normal::is_neg_i64_normal(a0, out),
        (TensorValue::U8(a0), TensorValue::Bool(out)) => super::kernels::normal::is_neg_u8_normal(a0, out),
        (TensorValue::U16(a0), TensorValue::Bool(out)) => super::kernels::normal::is_neg_u16_normal(a0, out),
        (TensorValue::U32(a0), TensorValue::Bool(out)) => super::kernels::normal::is_neg_u32_normal(a0, out),
        (TensorValue::U64(a0), TensorValue::Bool(out)) => super::kernels::normal::is_neg_u64_normal(a0, out),
        (TensorValue::I1(a0), TensorValue::Bool(out)) => super::kernels::packed::is_neg_i1_packed(a0, out),
        (TensorValue::I2(a0), TensorValue::Bool(out)) => super::kernels::packed::is_neg_i2_packed(a0, out),
        (TensorValue::I4(a0), TensorValue::Bool(out)) => super::kernels::packed::is_neg_i4_packed(a0, out),
        _ => Err(anyhow!("dtype mismatch")),
    }
}

