// @generated by build.rs. Do not edit.
use anyhow::{anyhow, Result};

use crate::graph::OpAttrs;
use crate::ops::cpu::registry::expect_output;
use crate::tensor::TensorValue;

pub fn max_normal_dispatch(_attrs: &OpAttrs, inputs: &[TensorValue], output: Option<&mut TensorValue>) -> Result<()> {
    let out = expect_output(output)?;
    match (&inputs[0], &inputs[1], out) {
        (TensorValue::F8(a0), TensorValue::F8(a1), TensorValue::F8(out)) => super::kernels::normal::max_f8_normal(a0, a1, out),
        (TensorValue::F16(a0), TensorValue::F16(a1), TensorValue::F16(out)) => super::kernels::normal::max_f16_normal(a0, a1, out),
        (TensorValue::BF16(a0), TensorValue::BF16(a1), TensorValue::BF16(out)) => super::kernels::normal::max_bf16_normal(a0, a1, out),
        (TensorValue::F32(a0), TensorValue::F32(a1), TensorValue::F32(out)) => super::kernels::normal::max_f32_normal(a0, a1, out),
        (TensorValue::F64(a0), TensorValue::F64(a1), TensorValue::F64(out)) => super::kernels::normal::max_f64_normal(a0, a1, out),
        (TensorValue::I8(a0), TensorValue::I8(a1), TensorValue::I8(out)) => super::kernels::normal::max_i8_normal(a0, a1, out),
        (TensorValue::I16(a0), TensorValue::I16(a1), TensorValue::I16(out)) => super::kernels::normal::max_i16_normal(a0, a1, out),
        (TensorValue::I32(a0), TensorValue::I32(a1), TensorValue::I32(out)) => super::kernels::normal::max_i32_normal(a0, a1, out),
        (TensorValue::I64(a0), TensorValue::I64(a1), TensorValue::I64(out)) => super::kernels::normal::max_i64_normal(a0, a1, out),
        (TensorValue::U8(a0), TensorValue::U8(a1), TensorValue::U8(out)) => super::kernels::normal::max_u8_normal(a0, a1, out),
        (TensorValue::U16(a0), TensorValue::U16(a1), TensorValue::U16(out)) => super::kernels::normal::max_u16_normal(a0, a1, out),
        (TensorValue::U32(a0), TensorValue::U32(a1), TensorValue::U32(out)) => super::kernels::normal::max_u32_normal(a0, a1, out),
        (TensorValue::U64(a0), TensorValue::U64(a1), TensorValue::U64(out)) => super::kernels::normal::max_u64_normal(a0, a1, out),
        (TensorValue::I1(a0), TensorValue::I1(a1), TensorValue::I1(out)) => super::kernels::packed::max_i1_packed(a0, a1, out),
        (TensorValue::I2(a0), TensorValue::I2(a1), TensorValue::I2(out)) => super::kernels::packed::max_i2_packed(a0, a1, out),
        (TensorValue::I4(a0), TensorValue::I4(a1), TensorValue::I4(out)) => super::kernels::packed::max_i4_packed(a0, a1, out),
        (TensorValue::U1(a0), TensorValue::U1(a1), TensorValue::U1(out)) => super::kernels::packed::max_u1_packed(a0, a1, out),
        (TensorValue::U2(a0), TensorValue::U2(a1), TensorValue::U2(out)) => super::kernels::packed::max_u2_packed(a0, a1, out),
        (TensorValue::U4(a0), TensorValue::U4(a1), TensorValue::U4(out)) => super::kernels::packed::max_u4_packed(a0, a1, out),
        _ => Err(anyhow!("dtype mismatch")),
    }
}

pub fn max_inplace_dispatch(_attrs: &OpAttrs, inputs: &[TensorValue], output: Option<&mut TensorValue>) -> Result<()> {
    let out = expect_output(output)?;
    match (out, &inputs[1]) {
        (TensorValue::F8(a0), TensorValue::F8(a1)) => super::kernels::normal::max_f8_inplace(a0, a1),
        (TensorValue::F16(a0), TensorValue::F16(a1)) => super::kernels::normal::max_f16_inplace(a0, a1),
        (TensorValue::BF16(a0), TensorValue::BF16(a1)) => super::kernels::normal::max_bf16_inplace(a0, a1),
        (TensorValue::F32(a0), TensorValue::F32(a1)) => super::kernels::normal::max_f32_inplace(a0, a1),
        (TensorValue::F64(a0), TensorValue::F64(a1)) => super::kernels::normal::max_f64_inplace(a0, a1),
        (TensorValue::I8(a0), TensorValue::I8(a1)) => super::kernels::normal::max_i8_inplace(a0, a1),
        (TensorValue::I16(a0), TensorValue::I16(a1)) => super::kernels::normal::max_i16_inplace(a0, a1),
        (TensorValue::I32(a0), TensorValue::I32(a1)) => super::kernels::normal::max_i32_inplace(a0, a1),
        (TensorValue::I64(a0), TensorValue::I64(a1)) => super::kernels::normal::max_i64_inplace(a0, a1),
        (TensorValue::U8(a0), TensorValue::U8(a1)) => super::kernels::normal::max_u8_inplace(a0, a1),
        (TensorValue::U16(a0), TensorValue::U16(a1)) => super::kernels::normal::max_u16_inplace(a0, a1),
        (TensorValue::U32(a0), TensorValue::U32(a1)) => super::kernels::normal::max_u32_inplace(a0, a1),
        (TensorValue::U64(a0), TensorValue::U64(a1)) => super::kernels::normal::max_u64_inplace(a0, a1),
        (TensorValue::I1(a0), TensorValue::I1(a1)) => super::kernels::packed::max_i1_packed_inplace(a0, a1),
        (TensorValue::I2(a0), TensorValue::I2(a1)) => super::kernels::packed::max_i2_packed_inplace(a0, a1),
        (TensorValue::I4(a0), TensorValue::I4(a1)) => super::kernels::packed::max_i4_packed_inplace(a0, a1),
        (TensorValue::U1(a0), TensorValue::U1(a1)) => super::kernels::packed::max_u1_packed_inplace(a0, a1),
        (TensorValue::U2(a0), TensorValue::U2(a1)) => super::kernels::packed::max_u2_packed_inplace(a0, a1),
        (TensorValue::U4(a0), TensorValue::U4(a1)) => super::kernels::packed::max_u4_packed_inplace(a0, a1),
        _ => Err(anyhow!("dtype mismatch")),
    }
}

