// @generated by build.rs. Do not edit.
use anyhow::{anyhow, Result};

use crate::graph::OpAttrs;
use crate::ops::cpu::registry::expect_output;
use crate::tensor::TensorValue;

pub fn trunc_normal_dispatch(_attrs: &OpAttrs, inputs: &[TensorValue], output: Option<&mut TensorValue>) -> Result<()> {
    let out = expect_output(output)?;
    match (&inputs[0], out) {
        (TensorValue::F8(a0), TensorValue::F8(out)) => super::kernels::normal::trunc_f8_normal(a0, out),
        (TensorValue::F16(a0), TensorValue::F16(out)) => super::kernels::normal::trunc_f16_normal(a0, out),
        (TensorValue::BF16(a0), TensorValue::BF16(out)) => super::kernels::normal::trunc_bf16_normal(a0, out),
        (TensorValue::F32(a0), TensorValue::F32(out)) => super::kernels::normal::trunc_f32_normal(a0, out),
        (TensorValue::F64(a0), TensorValue::F64(out)) => super::kernels::normal::trunc_f64_normal(a0, out),
        _ => Err(anyhow!("dtype mismatch")),
    }
}

pub fn trunc_inplace_dispatch(_attrs: &OpAttrs, _inputs: &[TensorValue], output: Option<&mut TensorValue>) -> Result<()> {
    let out = expect_output(output)?;
    match out {
        TensorValue::F8(a) => super::kernels::normal::trunc_f8_inplace(a),
        TensorValue::F16(a) => super::kernels::normal::trunc_f16_inplace(a),
        TensorValue::BF16(a) => super::kernels::normal::trunc_bf16_inplace(a),
        TensorValue::F32(a) => super::kernels::normal::trunc_f32_inplace(a),
        TensorValue::F64(a) => super::kernels::normal::trunc_f64_inplace(a),
        _ => Err(anyhow!("dtype mismatch")),
    }
}

