// @generated by build.rs. Do not edit.
use anyhow::{anyhow, Result};

use crate::graph::OpAttrs;
use crate::ops::cpu::registry::expect_output;
use crate::tensor::TensorValue;

pub fn clamp_normal_dispatch(_attrs: &OpAttrs, inputs: &[TensorValue], output: Option<&mut TensorValue>) -> Result<()> {
    let out = expect_output(output)?;
    match (&inputs[0], out) {
        (TensorValue::F8(a0), TensorValue::F8(out)) => super::kernels::normal::clamp_f8_normal(_attrs, a0, out),
        (TensorValue::F16(a0), TensorValue::F16(out)) => super::kernels::normal::clamp_f16_normal(_attrs, a0, out),
        (TensorValue::BF16(a0), TensorValue::BF16(out)) => super::kernels::normal::clamp_bf16_normal(_attrs, a0, out),
        (TensorValue::F32(a0), TensorValue::F32(out)) => super::kernels::normal::clamp_f32_normal(_attrs, a0, out),
        (TensorValue::F64(a0), TensorValue::F64(out)) => super::kernels::normal::clamp_f64_normal(_attrs, a0, out),
        (TensorValue::I8(a0), TensorValue::I8(out)) => super::kernels::normal::clamp_i8_normal(_attrs, a0, out),
        (TensorValue::I16(a0), TensorValue::I16(out)) => super::kernels::normal::clamp_i16_normal(_attrs, a0, out),
        (TensorValue::I32(a0), TensorValue::I32(out)) => super::kernels::normal::clamp_i32_normal(_attrs, a0, out),
        (TensorValue::I64(a0), TensorValue::I64(out)) => super::kernels::normal::clamp_i64_normal(_attrs, a0, out),
        (TensorValue::U8(a0), TensorValue::U8(out)) => super::kernels::normal::clamp_u8_normal(_attrs, a0, out),
        (TensorValue::U16(a0), TensorValue::U16(out)) => super::kernels::normal::clamp_u16_normal(_attrs, a0, out),
        (TensorValue::U32(a0), TensorValue::U32(out)) => super::kernels::normal::clamp_u32_normal(_attrs, a0, out),
        (TensorValue::U64(a0), TensorValue::U64(out)) => super::kernels::normal::clamp_u64_normal(_attrs, a0, out),
        (TensorValue::I1(a0), TensorValue::I1(out)) => super::kernels::packed::clamp_i1_packed(_attrs, a0, out),
        (TensorValue::I2(a0), TensorValue::I2(out)) => super::kernels::packed::clamp_i2_packed(_attrs, a0, out),
        (TensorValue::I4(a0), TensorValue::I4(out)) => super::kernels::packed::clamp_i4_packed(_attrs, a0, out),
        (TensorValue::U1(a0), TensorValue::U1(out)) => super::kernels::packed::clamp_u1_packed(_attrs, a0, out),
        (TensorValue::U2(a0), TensorValue::U2(out)) => super::kernels::packed::clamp_u2_packed(_attrs, a0, out),
        (TensorValue::U4(a0), TensorValue::U4(out)) => super::kernels::packed::clamp_u4_packed(_attrs, a0, out),
        _ => Err(anyhow!("dtype mismatch")),
    }
}

pub fn clamp_inplace_dispatch(_attrs: &OpAttrs, _inputs: &[TensorValue], output: Option<&mut TensorValue>) -> Result<()> {
    let out = expect_output(output)?;
    match out {
        TensorValue::F8(a) => super::kernels::normal::clamp_f8_inplace(_attrs, a),
        TensorValue::F16(a) => super::kernels::normal::clamp_f16_inplace(_attrs, a),
        TensorValue::BF16(a) => super::kernels::normal::clamp_bf16_inplace(_attrs, a),
        TensorValue::F32(a) => super::kernels::normal::clamp_f32_inplace(_attrs, a),
        TensorValue::F64(a) => super::kernels::normal::clamp_f64_inplace(_attrs, a),
        TensorValue::I8(a) => super::kernels::normal::clamp_i8_inplace(_attrs, a),
        TensorValue::I16(a) => super::kernels::normal::clamp_i16_inplace(_attrs, a),
        TensorValue::I32(a) => super::kernels::normal::clamp_i32_inplace(_attrs, a),
        TensorValue::I64(a) => super::kernels::normal::clamp_i64_inplace(_attrs, a),
        TensorValue::U8(a) => super::kernels::normal::clamp_u8_inplace(_attrs, a),
        TensorValue::U16(a) => super::kernels::normal::clamp_u16_inplace(_attrs, a),
        TensorValue::U32(a) => super::kernels::normal::clamp_u32_inplace(_attrs, a),
        TensorValue::U64(a) => super::kernels::normal::clamp_u64_inplace(_attrs, a),
        TensorValue::I1(a) => super::kernels::packed::clamp_i1_packed_inplace(_attrs, a),
        TensorValue::I2(a) => super::kernels::packed::clamp_i2_packed_inplace(_attrs, a),
        TensorValue::I4(a) => super::kernels::packed::clamp_i4_packed_inplace(_attrs, a),
        TensorValue::U1(a) => super::kernels::packed::clamp_u1_packed_inplace(_attrs, a),
        TensorValue::U2(a) => super::kernels::packed::clamp_u2_packed_inplace(_attrs, a),
        TensorValue::U4(a) => super::kernels::packed::clamp_u4_packed_inplace(_attrs, a),
        _ => Err(anyhow!("dtype mismatch")),
    }
}

